services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: HadjHassineJawher
      POSTGRES_PASSWORD: changeit
      POSTGRES_DB: product_images_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - db_network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - db_network

volumes:
  postgres-data:

networks:
  db_network:
    driver: bridge
